# Spring Framework and application log
logging.level.org.springframework=info
logging.level.com.cognizant=debug

# Hibernate logs for displaying executed SQL, input and output
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.type.descriptor.sql=trace

# Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=renegade@123

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
# Let Spring Boot automatically detect the best MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect